// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xyzies.TWC.Public.Data;

namespace Xyzies.TWC.Public.Data.Migrations.AppData
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20191030101255_AddTenant")]
    partial class AddTenant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("BranchName");

                    b.Property<string>("City");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("GeoLat");

                    b.Property<string>("GeoLng");

                    b.Property<bool>("IsEnabled");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Phone");

                    b.Property<string>("State");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.BranchContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid>("BranchContactTypeId");

                    b.Property<Guid>("BranchId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("PersonLastName");

                    b.Property<string>("PersonName");

                    b.Property<string>("PersonTitle");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("BranchContactTypeId");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchContact");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.BranchContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BranchContactType");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountManager");

                    b.Property<string>("ActivityStatus");

                    b.Property<string>("Address");

                    b.Property<int?>("Agentid");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<string>("BankAccountNumber");

                    b.Property<bool?>("BankInfoGiven");

                    b.Property<string>("BankName");

                    b.Property<string>("BankNumber");

                    b.Property<string>("BusinessDescription");

                    b.Property<int?>("BusinessSource");

                    b.Property<string>("CallerId");

                    b.Property<string>("CellNumber");

                    b.Property<string>("City");

                    b.Property<Guid?>("CompanyKey");

                    b.Property<string>("CompanyName");

                    b.Property<int?>("CompanyTenantId");

                    b.Property<Guid?>("CompanyStatusKey");

                    b.Property<byte?>("CompanyType");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("CrmCompanyId");

                    b.Property<int?>("CustomerDemographicId");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("FedId");

                    b.Property<string>("FirstName");

                    b.Property<string>("GeoLat");

                    b.Property<string>("GeoLon");

                    b.Property<bool?>("IsAgreement");

                    b.Property<bool?>("IsCallCenter");

                    b.Property<bool>("IsEnabled");

                    b.Property<bool?>("IsMarketPlace");

                    b.Property<bool?>("IsOwnerPassBackground");

                    b.Property<bool?>("IsSellsLifelineWireless");

                    b.Property<bool?>("IsSpectrum");

                    b.Property<bool?>("IsWebsite");

                    b.Property<string>("LastName");

                    b.Property<string>("LegalName");

                    b.Property<int?>("LocationTypeId");

                    b.Property<string>("MarketPlaceName");

                    b.Property<string>("MarketStrategy");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("NumberofStores");

                    b.Property<int?>("ParentCompanyId");

                    b.Property<int?>("PaymentMode");

                    b.Property<string>("Phone");

                    b.Property<string>("PhysicalName");

                    b.Property<string>("PrimaryContactName");

                    b.Property<string>("PrimaryContactTitle");

                    b.Property<string>("RetailerGoogleAccount");

                    b.Property<string>("RetailerGooglePassword");

                    b.Property<Guid?>("RetailerGroupKey");

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("SocialMediaAccount");

                    b.Property<string>("State");

                    b.Property<string>("StateEstablished");

                    b.Property<int?>("Status");

                    b.Property<int?>("StoreID");

                    b.Property<int?>("StoreLocationCount");

                    b.Property<Guid?>("TeamKey");

                    b.Property<int?>("TypeOfCompany");

                    b.Property<string>("WebsiteList");

                    b.Property<string>("XyziesId");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTenantId");

                    b.HasIndex("CompanyStatusKey");

                    b.HasIndex("TenantId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.RequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StatusKey");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int?>("DisplaySeq");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnName("StatusName");

                    b.Property<string>("ProcedureName");

                    b.Property<string>("Reason");

                    b.Property<Guid>("WfKey");

                    b.HasKey("Id");

                    b.ToTable("RequestStatus");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Tenant.CompanyTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("CompanyTenants");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Tenant.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("SeviceProviderName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active");

                    b.Property<string>("Address");

                    b.Property<Guid?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<string>("City");

                    b.Property<int?>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("IPAddressRestriction");

                    b.Property<string>("Imagename");

                    b.Property<bool?>("IsEmailVerified");

                    b.Property<bool?>("IsIdentityUploaded");

                    b.Property<bool?>("IsPhoneVerified");

                    b.Property<bool?>("IsUserPictureUploaded");

                    b.Property<bool?>("Is_Agreement");

                    b.Property<string>("LastName");

                    b.Property<string>("LoginIpAddress");

                    b.Property<int?>("ManagedBy");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTime?>("PasswordExpiryOn");

                    b.Property<string>("Phone");

                    b.Property<string>("PhotoID");

                    b.Property<string>("Role");

                    b.Property<int?>("SalesPersonID");

                    b.Property<string>("SocialMediaAccount");

                    b.Property<string>("State");

                    b.Property<int?>("StatusId");

                    b.Property<Guid?>("UserGuid");

                    b.Property<int?>("UserRefID");

                    b.Property<string>("XyziesId");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Branch", b =>
                {
                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.BranchContact", b =>
                {
                    b.HasOne("Xyzies.TWC.Public.Data.Entities.BranchContactType", "BranchContactType")
                        .WithMany()
                        .HasForeignKey("BranchContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Branch", "Branch")
                        .WithMany("BranchContacts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Company", b =>
                {
                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Tenant.CompanyTenant")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTenantId");

                    b.HasOne("Xyzies.TWC.Public.Data.Entities.RequestStatus", "RequestStatus")
                        .WithMany()
                        .HasForeignKey("CompanyStatusKey");

                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Tenant.Tenant")
                        .WithMany("Companies")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("Xyzies.TWC.Public.Data.Entities.Users", b =>
                {
                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Branch")
                        .WithMany("BranchUsers")
                        .HasForeignKey("BranchId");

                    b.HasOne("Xyzies.TWC.Public.Data.Entities.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
