// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xyzies.SSO.Identity.Data;

namespace Xyzies.SSO.Identity.Data.Migrations
{
    [DbContext(typeof(IdentityDataContext))]
    [Migration("20190212153144_IdentityStructure")]
    partial class IdentityStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Scope")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Relationship.PermissionToPolicy", b =>
                {
                    b.Property<Guid>("Relation1Id")
                        .HasColumnName("PermissionId");

                    b.Property<Guid>("Relation2Id")
                        .HasColumnName("PolicyId");

                    b.HasKey("Relation1Id", "Relation2Id");

                    b.HasIndex("Relation2Id");

                    b.ToTable("PermissionToPolicy");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Relationship.PolicyToRole", b =>
                {
                    b.Property<Guid>("Relation1Id")
                        .HasColumnName("PolicyId");

                    b.Property<Guid>("Relation2Id")
                        .HasColumnName("RoleId");

                    b.HasKey("Relation1Id", "Relation2Id");

                    b.HasIndex("Relation2Id");

                    b.ToTable("PolicyToRole");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleKey");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsCustom");

                    b.Property<int?>("RoleId");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("TWC_Role");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<int?>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("IPAddressRestriction");

                    b.Property<string>("ImageName")
                        .HasColumnName("imagename");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("Active");

                    b.Property<bool?>("IsAgreement")
                        .HasColumnName("is_Agreement");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("deleted");

                    b.Property<bool?>("IsEmailVerified");

                    b.Property<bool?>("IsIdentityUploaded");

                    b.Property<bool?>("IsPhoneVerified");

                    b.Property<string>("LastName");

                    b.Property<int>("ManagedBy");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTime>("PasswordExpiryOn");

                    b.Property<string>("Phone");

                    b.Property<string>("Role");

                    b.Property<int?>("SalesPersonID");

                    b.Property<string>("State");

                    b.Property<int?>("StatusId");

                    b.Property<Guid?>("UserGuid");

                    b.Property<int?>("UserRefID");

                    b.Property<string>("XyziesId");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("TWC_Users");
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Relationship.PermissionToPolicy", b =>
                {
                    b.HasOne("Xyzies.SSO.Identity.Data.Entity.Permission", "Entity1")
                        .WithMany()
                        .HasForeignKey("Relation1Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Xyzies.SSO.Identity.Data.Entity.Policy", "Entity2")
                        .WithMany("RelationToPermission")
                        .HasForeignKey("Relation2Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xyzies.SSO.Identity.Data.Entity.Relationship.PolicyToRole", b =>
                {
                    b.HasOne("Xyzies.SSO.Identity.Data.Entity.Policy", "Entity1")
                        .WithMany("RelationToRole")
                        .HasForeignKey("Relation1Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Xyzies.SSO.Identity.Data.Entity.Role", "Entity2")
                        .WithMany("RelationToPolicy")
                        .HasForeignKey("Relation2Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
